Added colored ERROR messages to git extensions

diff --git a/git-tools/bin/git-bootstrap b/git-tools/bin/git-bootstrap
--- a/git-tools/bin/git-bootstrap
+++ b/git-tools/bin/git-bootstrap
@@ -28,7 +28,7 @@ if [ "$#" -gt 0 ]; then
         case "$OPT" in
             --dir|-d) shift; PROJECT_DIR="$1" ;;
             --help) usage; exit 0 ;;
-            *) echo "[ERROR] Unknown option."; usage; exit 1 ;;
+            *) echo "$(tput setaf 1)[ERROR]$(tput sgr0) Unknown option."; usage; exit 1 ;;
         esac
         shift
     done
diff --git a/git-tools/bin/git-hooks b/git-tools/bin/git-hooks
--- a/git-tools/bin/git-hooks
+++ b/git-tools/bin/git-hooks
@@ -7,6 +7,8 @@
 
 set -eo pipefail
 
+ERROR="$(tput setaf 1)[ERROR]$(tput sgr0)"
+
 usage() {
     echo "git-hooks"
     echo
@@ -27,7 +29,7 @@ if [ "$#" -gt 0 ]; then
             --clean) CLEAN=1 ;;
             --help|-h) usage; exit 0 ;;
             --type|-t) shift; HOOKS="$1" ;;
-            *) echo "[ERROR] Unrecognized option \`$OPT\`."; usage; exit 1 ;;
+            *) echo "$ERROR Unrecognized option \`$OPT\`."; usage; exit 1 ;;
         esac
         shift
     done
@@ -35,7 +37,7 @@ fi
 
 if [ -z "$HOOKS" ]
 then
-    echo "[ERROR] No hooks given."
+    echo "$ERROR No hooks given."
     usage
     exit 1
 fi
@@ -77,7 +79,7 @@ do
             fi
         done
     else
-        echo "$(tput setaf 1)[ERROR]$(tput sgr0) Could not install Git hooks."
+        echo "$ERROR Could not install Git hooks."
     fi
 done
 
