Started replacing {echo,printf}

diff --git a/git-tools/bin/git-bootstrap b/git-tools/bin/git-bootstrap
--- a/git-tools/bin/git-bootstrap
+++ b/git-tools/bin/git-bootstrap
@@ -11,15 +11,15 @@ set -eo pipefail
 PROJECT_DIR=
 
 usage() {
-    echo "git-bootstrap"
-    echo
-    echo "Usage: $0 [args]"
-    echo
-    echo "Args:"
-    echo "--dir, -d   The git directory into which the files will be copied."
-    echo "--help      Help."
-    echo
-    echo "Truthfully, this doesn't use any \`git\` commands.  Oh well."
+    printf "git-bootstrap
+
+Usage: %s [args]
+
+Args:
+--dir, -d   The git directory into which the files will be copied.
+--help      Help.
+
+Truthfully, this doesn't use any \`git\` commands.  Oh well.\n" "$0"
 }
 
 if [ "$#" -gt 0 ]; then
@@ -28,7 +28,7 @@ if [ "$#" -gt 0 ]; then
         case "$OPT" in
             --dir|-d) shift; PROJECT_DIR="$1" ;;
             --help) usage; exit 0 ;;
-            *) echo "$ERROR Unknown option."; usage; exit 1 ;;
+            *) printf "%b Unknown option.\n" "$ERROR"; usage; exit 1 ;;
         esac
         shift
     done
@@ -48,5 +48,5 @@ do
     fi
 done
 
-echo "$INFO Installed bootstrap files into $PROJECT_DIR."
+printf "%b Installed bootstrap files into %s.\n" "$INFO" "$PROJECT_DIR"
 
diff --git a/git-tools/bin/git-hooks b/git-tools/bin/git-hooks
--- a/git-tools/bin/git-hooks
+++ b/git-tools/bin/git-hooks
@@ -8,16 +8,16 @@
 set -eo pipefail
 
 usage() {
-    echo "git-hooks"
-    echo
-    echo "Usage: git hooks --hooks TYPES"
-    echo
-    echo "Args:"
-    echo "--clean       Before installing any hooks, delete .git/hooks/pre-commit*"
-    echo "--help,  -h   Help."
-    echo "--type,  -t   Comma-separated string of directory names that hold the"
-    echo "              hooks to be installed."
-    echo "              Types: go, js, py, _ (misc)"
+    printf "git-hooks
+
+Usage: git hooks --hooks TYPES
+
+Args:
+--clean       Before installing any hooks, delete .git/hooks/pre-commit*
+--help,  -h   Help.
+--type,  -t   Comma-separated string of directory names that hold the
+              hooks to be installed.
+              Types: go, js, py, _ (misc)\n"
 }
 
 if [ "$#" -gt 0 ]; then
@@ -27,7 +27,7 @@ if [ "$#" -gt 0 ]; then
             --clean) CLEAN=1 ;;
             --help|-h) usage; exit 0 ;;
             --type|-t) shift; HOOKS="$1" ;;
-            *) echo "$ERROR Unrecognized option \`$OPT\`."; usage; exit 1 ;;
+            *) printf "%b Unrecognized option \`%s\`.\n" "$ERROR" "$OPT"; usage; exit 1 ;;
         esac
         shift
     done
@@ -35,7 +35,7 @@ fi
 
 if [ -z "$HOOKS" ]
 then
-    echo "$ERROR No hooks given."
+    printf "%b No hooks given.\n" "$ERROR"
     usage
     exit 1
 fi
@@ -77,7 +77,7 @@ do
             fi
         done
     else
-        echo "$ERROR Could not install Git hooks."
+        printf "%b Could not install Git hooks.\n" "$ERROR"
     fi
 done
 
diff --git a/git-tools/bin/git-init-wrapper b/git-tools/bin/git-init-wrapper
--- a/git-tools/bin/git-init-wrapper
+++ b/git-tools/bin/git-init-wrapper
@@ -7,15 +7,15 @@ HOOKS=
 GIT_DIR=
 
 usage() {
-    echo "git-init-wrapper"
-    echo
-    echo "Usage: git init-wrapper [args]"
-    echo
-    echo "Args:"
-    echo "--dir,   -d   If provided, the directory in which git will be initiated."
-    echo "--help,  -h   Help."
-    echo "--hooks, -t   Comma-separated string of directory names that hold the"
-    echo "              hooks to be installed."
+    printf "git-init-wrapper
+
+Usage: git init-wrapper [args]
+
+Args:
+--dir,   -d   If provided, the directory in which git will be initiated.
+--help,  -h   Help.
+--hooks, -t   Comma-separated string of directory names that hold the
+              hooks to be installed."
 }
 
 if [ "$#" -gt 0 ]; then
@@ -25,7 +25,7 @@ if [ "$#" -gt 0 ]; then
             --dir|-d) shift; GIT_DIR="$1" ;;
             --hooks|-t) shift; HOOKS="$1" ;;
             --help|-h) usage; exit 0 ;;
-            *) echo "$ERROR Unrecognized option \`$OPT\`."; usage; exit 1 ;;
+            *) printf "%b Unrecognized option \`%s\`.\n" "$ERROR" "$OPT"; usage; exit 1 ;;
         esac
         shift
     done
@@ -47,6 +47,6 @@ then
     git hooks --type "$HOOKS"
     popd > /dev/null
 else
-    echo "$INFO No git hooks installed."
+    printf "%b No git hooks installed.\n" "$INFO"
 fi
 
