Removed tput in favor of terminal chars

diff --git a/git-tools/bin/git-bootstrap b/git-tools/bin/git-bootstrap
--- a/git-tools/bin/git-bootstrap
+++ b/git-tools/bin/git-bootstrap
@@ -28,7 +28,7 @@ if [ "$#" -gt 0 ]; then
         case "$OPT" in
             --dir|-d) shift; PROJECT_DIR="$1" ;;
             --help) usage; exit 0 ;;
-            *) echo "$(tput setaf 1)[ERROR]$(tput sgr0) Unknown option."; usage; exit 1 ;;
+            *) echo "$ERROR Unknown option."; usage; exit 1 ;;
         esac
         shift
     done
@@ -48,5 +48,5 @@ do
     fi
 done
 
-echo "$(tput setaf 2)[INFO]$(tput sgr0) Installed bootstrap files into $PROJECT_DIR."
+echo "$INFO Installed bootstrap files into $PROJECT_DIR."
 
diff --git a/git-tools/bin/git-init-wrapper b/git-tools/bin/git-init-wrapper
--- a/git-tools/bin/git-init-wrapper
+++ b/git-tools/bin/git-init-wrapper
@@ -25,7 +25,7 @@ if [ "$#" -gt 0 ]; then
             --dir|-d) shift; GIT_DIR="$1" ;;
             --hooks|-t) shift; HOOKS="$1" ;;
             --help|-h) usage; exit 0 ;;
-            *) echo "$(tput setaf 1)[ERROR]$(tput sgr0) Unrecognized option \`$OPT\`."; usage; exit 1 ;;
+            *) echo "$ERROR Unrecognized option \`$OPT\`."; usage; exit 1 ;;
         esac
         shift
     done
@@ -47,6 +47,6 @@ then
     git hooks --type "$HOOKS"
     popd > /dev/null
 else
-    echo "$(tput setaf 2)[INFO]$(tput sgr0) No git hooks installed."
+    echo "$INFO No git hooks installed."
 fi
 
