Improved `git-hub` script
This enhancement allows the file to be referenced anywhere on the
filesystem.  For example:

- git hub -f ~/projects/hangman/hangman/__init__.py
- git hub -f git-hub

diff --git a/git-hub/bin/git-hub b/git-hub/bin/git-hub
--- a/git-hub/bin/git-hub
+++ b/git-hub/bin/git-hub
@@ -1,7 +1,5 @@
 #!/bin/bash
 #
-# http://stackoverflow.com/a/15802301
-#
 # Note that if listing a directory, Git Hub will replace the word
 # 'blob' in the url with 'tree', e.g.:
 #
@@ -9,14 +7,14 @@
 # becomes
 # https://github.com/btoll/git/tree/master/bin
 #
-# and vice-versa if viewing a file (i.e., 'tree' => 'blob').
+# and vice-versa if viewing a file (i.e., "tree" => "blob").
 #
 
-set -o pipefail
+set -eo pipefail
 
 ARCH=$(uname)
 BLAME=false
-BRANCH=$(git rev-parse --abbrev-ref HEAD)
+BRANCH=
 FILE=
 GET_HASH=
 HASH=
@@ -24,17 +22,7 @@ RANGE=
 REL_PATH=
 REMOTE_BRANCH=
 TOKEN=
-URL=
-
-if git rev-parse --is-inside-git-dir = true; then
-    echo "[ERROR]: Object is inside \`.git\` directory, exiting..."
-    exit 1
-fi
-
-if git rev-parse --is-inside-work-tree = false; then
-    echo "[ERROR]: Object is not under version control, exiting..."
-    exit 1
-fi
+GITHUB_URL=
 
 usage() {
     echo "GIT-HUB"
@@ -65,22 +53,23 @@ usage() {
     echo
 }
 
-setGitHubUrl() {
-    GITHUB_URL=$(git ls-remote --get-url)
+set_github_url() {
+    local url
+    url=$(git ls-remote --get-url)
 
     # If $GITHUB_URL begins with "git", i.e., git@github.com:btoll/utley
-    if [[ "$GITHUB_URL" == git* ]]; then
+    if [[ "$url" == git* ]]; then
         # Replaces first match of ":" with "/".
-        URL=${GITHUB_URL/://}
+        GITHUB_URL=${url/://}
 
         # Replaces first match of "git@" with "https://".
-        URL=${URL/git@/https://}
+        GITHUB_URL=${GITHUB_URL/git@/https://}
     fi
 
-    # If $URL ends with ".git", i.e., btoll/stymie.git
-    if [[ "$URL" == *.git ]]; then
+    # If $GITHUB_URL ends with ".git", i.e., btoll/stymie.git
+    if [[ "$GITHUB_URL" == *.git ]]; then
         # Cut ".git"
-        URL=${URL%.git}
+        GITHUB_URL=${GITHUB_URL%.git}
     fi
 }
 
@@ -98,7 +87,22 @@ while [ "$#" -gt 0 ]; do
     shift
 done
 
-setGitHubUrl
+# Files could be referenced anywhere in the filesystem, so we need to get
+# certain values from the git repo where the file is an object.
+pushd "$(dirname "$FILE")" > /dev/null
+
+if [ "$(git rev-parse --is-inside-work-tree)" = false ]; then
+    echo "[ERROR]: Object is not under version control, exiting..."
+    exit 1
+fi
+
+set_github_url
+
+# Get the path of the cwd relative to the top-level dir.
+REL_PATH=$(git rev-parse --show-prefix)
+BRANCH=$(git rev-parse --abbrev-ref HEAD)
+
+popd > /dev/null
 
 if [[ ( -n "$HASH" ) || ( -n "$GET_HASH" ) ]]; then
     # If given a branch name or tag, simply get its hash.
@@ -106,13 +110,10 @@ if [[ ( -n "$HASH" ) || ( -n "$GET_HASH" ) ]]; then
         HASH=$(git rev-parse "$GET_HASH")
     fi
 
-    URL+="/commit/$HASH"
+    GITHUB_URL+="/commit/$HASH"
 else
-    # Get the path of the cwd relative to the top-level dir.
-    REL_PATH=$(git rev-parse --show-prefix)
-
     if [ -n "$FILE" ]; then
-        REL_PATH+="$FILE"
+        REL_PATH+=$(basename "$FILE")
     fi
 
     if [[ -n "$REMOTE_BRANCH" ]]; then
@@ -120,22 +121,20 @@ else
     fi
 
     # If the relative path is empty, then we know that it's the top-level dir.
-    # In this case, don't futz with the url.
+    # In this case, don't futz with the url and skip this conditional.
     if [ -n "$REL_PATH" ]; then
         TOKEN=$($BLAME && echo "blame" || echo "blob")
-        URL+="/$TOKEN/$BRANCH/$REL_PATH"
+        GITHUB_URL+="/$TOKEN/$BRANCH/$REL_PATH"
     fi
 fi
 
 if [ -n "$RANGE" ]; then
-    URL+="#$RANGE"
+    GITHUB_URL+="#$RANGE"
 fi
 
-echo "$URL"
-
 if [ "$ARCH" == "Linux" ]; then
-    xdg-open "$URL" 2> /dev/null
+    xdg-open "$GITHUB_URL" 2> /dev/null
 else
-    open "$URL" 2> /dev/null
+    open "$GITHUB_URL" 2> /dev/null
 fi
 
